name: Deploy Frontend to S3 & CloudFront

on:
  push:
    branches:
      - develop # Adjust to your deployment branch
    # paths:
    #   - 'web-react-ts/**' # Only trigger when frontend files change

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup npm authentication
        run: |
          echo "@jaedag:registry=https://npm.pkg.github.com" > .npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.PAT_TOKEN }}" >> .npmrc
        working-directory: ./web-react-ts

      - name: Cache Node.js modules
        uses: actions/cache@v3
        with:
          path: web-react-ts/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('web-react-ts/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Dependencies
        run: npm install
        working-directory: ./web-react-ts

      - name: Retrieve Secrets from AWS Secrets Manager
        run: |
          export VITE_AUTH0_AUDIENCE=$(aws secretsmanager get-secret-value --secret-id VITE_AUTH0_AUDIENCE --query SecretString --output text)
          export VITE_AUTH0_CLIENT_ID=$(aws secretsmanager get-secret-value --secret-id VITE_AUTH0_CLIENT_ID --query SecretString --output text)
          export VITE_AUTH0_DOMAIN=$(aws secretsmanager get-secret-value --secret-id VITE_AUTH0_DOMAIN --query SecretString --output text)
          export VITE_CLOUDINARY_BANKING=$(aws secretsmanager get-secret-value --secret-id VITE_CLOUDINARY_BANKING --query SecretString --output text)
          export VITE_CLOUDINARY_BUSSING=$(aws secretsmanager get-secret-value --secret-id VITE_CLOUDINARY_BUSSING --query SecretString --output text)
          export VITE_CLOUDINARY_BUS_MOBILISATION=$(aws secretsmanager get-secret-value --secret-id VITE_CLOUDINARY_BUS_MOBILISATION --query SecretString --output text)
          export VITE_CLOUDINARY_MEMBERS=$(aws secretsmanager get-secret-value --secret-id VITE_CLOUDINARY_MEMBERS --query SecretString --output text)
          export VITE_CLOUDINARY_SERVICES=$(aws secretsmanager get-secret-value --secret-id VITE_CLOUDINARY_SERVICES --query SecretString --output text)
          export VITE_CLOUDINARY_TREASURERS=$(aws secretsmanager get-secret-value --secret-id VITE_CLOUDINARY_TREASURERS --query SecretString --output text)
          export VITE_GOOGLE_MAPS_API_KEY=$(aws secretsmanager get-secret-value --secret-id VITE_GOOGLE_MAPS_API_KEY --query SecretString --output text)
          export VITE_GRAPHQL_URI=$(aws secretsmanager get-secret-value --secret-id VITE_GRAPHQL_URI --query SecretString --output text)
          export SENTRY_AUTH_TOKEN=$(aws secretsmanager get-secret-value --secret-id SENTRY_AUTH_TOKEN --query SecretString --output text)
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}

      - name: Build Vite App
        run: npm run build
        working-directory: ./web-react-ts
        env:
          VITE_AUTH0_AUDIENCE: $VITE_AUTH0_AUDIENCE
          VITE_AUTH0_CLIENT_ID: $VITE_AUTH0_CLIENT_ID
          VITE_AUTH0_DOMAIN: $VITE_AUTH0_DOMAIN
          VITE_CLOUDINARY_BANKING: $VITE_CLOUDINARY_BANKING
          VITE_CLOUDINARY_BUSSING: $VITE_CLOUDINARY_BUSSING
          VITE_CLOUDINARY_BUS_MOBILISATION: $VITE_CLOUDINARY_BUS_MOBILISATION
          VITE_CLOUDINARY_MEMBERS: $VITE_CLOUDINARY_MEMBERS
          VITE_CLOUDINARY_SERVICES: $VITE_CLOUDINARY_SERVICES
          VITE_CLOUDINARY_TREASURERS: $VITE_CLOUDINARY_TREASURERS
          VITE_GOOGLE_MAPS_API_KEY: $VITE_GOOGLE_MAPS_API_KEY
          VITE_GRAPHQL_URI: $VITE_GRAPHQL_URI
          SENTRY_AUTH_TOKEN: $SENTRY_AUTH_TOKEN

      - name: Generate build version
        run: node generate-build-version.js
        working-directory: ./web-react-ts

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://${{ secrets.S3_BUCKET_NAME }} --delete
        working-directory: ./web-react-ts

      - name: Invalidate CloudFront Cache
        run: aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"

      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow
          text: ':rocket: Successfully deployed FLC Admin Portal frontend to S3 and invalidated CloudFront cache'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        if: success()
